import { z } from "zod";
import { WALL_SEG_PX, WALL_TOP_PX } from "./walls.ts";

// Flat decor (#260): wallpapers and floor patterns. The third asset class, and the only one that
// may be raster.
//
// Why raster is safe here and nowhere else: a raster asset carries no DepthBox, so gateDrawOrder
// and gateSeatOcclusion cannot cover it (#233, #235). That only matters for things standing on
// the floor that avatars route around and sit on. A floor pattern IS the floor and a wallpaper IS
// the wall — both are already drawn as the flat backdrop everything else sorts against, so there
// is no ordering left to get wrong.
//
// The asset is one tile, and the client repeats it. Nothing is pre-projected: the tile is authored
// in the surface's own two axes and a texture matrix carries it into screen space, so the same
// bytes serve the left wall, the right wall and every raised floor height.
//
//   floor — the tile is screen-space, axis-aligned. Floor diamonds tessellate on the lattice
//           generated by (+32, +16) and (-32, +16), and a w x h rectangle repeats compatibly with
//           it exactly when w is a multiple of 64 and h a multiple of 32. That is why the cell is
//           two diamonds wide: the existing two-tone checker is the smallest legal pattern.
//   wall  — the tile is wall-space (u along the wall, v straight down), the same axes walls.ts
//           measures hanging items in. The client shears it by the wall's 2:1 axis at draw time.
//
// Colour comes from the same 91 the generator emits, so gatePalette still holds for the class.

export const DECOR_KINDS = ["floor", "wall"] as const;

const TileSchema = z.object({
  w: z.number().int().min(1),
  h: z.number().int().min(1),
});

export const DecorDefSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("floor"),
    id: z.string(),
    name: z.string(),
    tile: TileSchema,
    /** The two vertical faces a raised tile shows (client scene/room.ts). Flat colours, not
     *  raster: the floor tile is authored in the ground plane, and shearing it up a riser would
     *  read as a smear rather than as the same material turned on edge. */
    sides: z.object({ left: z.number().int(), right: z.number().int() }),
  }),
  z.object({
    kind: z.literal("wall"),
    id: z.string(),
    name: z.string(),
    tile: TileSchema,
    /** The wall's own thickness seen from above — the cap strip along the top edge. */
    cap: z.number().int(),
  }),
]);
export type DecorDef = z.infer<typeof DecorDefSchema>;

/** Screen-space lattice cell of the floor: the bounding box of one tile diamond at scale 64, and
 *  the smallest rectangle that repeats on the diamond lattice. */
export const FLOOR_CELL_W = 64;
export const FLOOR_CELL_H = 32;

/** Why a tile size is illegal for its surface, or null when it is legal. Shared so the gate and
 *  the authoring tool cannot drift apart. */
export function decorTileFault(def: DecorDef): string | null {
  const { w, h } = def.tile;
  if (def.kind === "floor") {
    if (w % FLOOR_CELL_W !== 0 || h % FLOOR_CELL_H !== 0) {
      return `floor tile ${w}x${h} is off the diamond lattice — width must be a multiple of ` +
        `${FLOOR_CELL_W} and height a multiple of ${FLOOR_CELL_H}, or the pattern shifts by half ` +
        `a tile every row`;
    }
    return null;
  }
  if (w % 2 !== 0) {
    return `wall tile width ${w} is odd — the wall's 2:1 axis drops half a screen pixel per ` +
      `along-wall pixel, so an odd repeat lands the pattern half a pixel off itself`;
  }
  if (WALL_SEG_PX % w !== 0) {
    return `wall tile width ${w} does not divide the ${WALL_SEG_PX} px segment — the pattern ` +
      `would be cut mid-motif at every segment boundary`;
  }
  if (WALL_TOP_PX % h !== 0) {
    return `wall tile height ${h} does not divide the ${WALL_TOP_PX} px wall — the pattern would ` +
      `be cut mid-motif at the floor line`;
  }
  return null;
}

export const DECOR_CATALOG: DecorDef[] = [
  {
    kind: "floor", id: "floor_marble", name: "Marble Chequer",
    tile: { w: 64, h: 32 },
    sides: { left: 0x656056, right: 0x768594 },
  },
  {
    kind: "floor", id: "floor_parquet", name: "Parquet",
    tile: { w: 64, h: 32 },
    sides: { left: 0x8b4513, right: 0xb55a19 },
  },
  {
    kind: "floor", id: "floor_planks", name: "Lodge Planks",
    tile: { w: 64, h: 32 },
    sides: { left: 0x8b4513, right: 0xb55a19 },
  },
  {
    kind: "wall", id: "wall_wainscot", name: "Wainscot Panelling",
    tile: { w: 16, h: 128 },
    cap: 0xcbc0ac,
  },
  {
    kind: "wall", id: "wall_logcabin", name: "Log Cabin",
    tile: { w: 32, h: 32 },
    cap: 0xcbc0ac,
  },
  {
    kind: "wall", id: "wall_pinstripe", name: "Casino Pinstripe",
    tile: { w: 16, h: 32 },
    cap: 0x8d9eb1,
  },
  // Pool & spa deck (#357). The water is two shades of one ramp because teal's shadow shade is
  // luma 74.5, under the 82 gateDecorContrast holds a backdrop to — a floor that dark stops an
  // avatar's outline reading against it.
  {
    kind: "floor", id: "floor_deck", name: "Pool Deck",
    tile: { w: 64, h: 32 },
    sides: { left: 0x7e6a46, right: 0xc2a36b },
  },
  {
    kind: "floor", id: "floor_pool", name: "Pool Water",
    tile: { w: 64, h: 32 },
    sides: { left: 0x2f8f8f, right: 0x3dbaba },
  },
  {
    // The deep end (#427). The same pattern with both shades one step down the ladder, so the
    // deep tile's highlight is the shallow tile's base and the two read as one body of water.
    // The step leaves teal at the dark end because teal's own next shade down (left, luma 74.5)
    // is under the 82 a backdrop needs — navy.right at 92 is the darkest blue the decor gamut
    // holds, and #435 already found that "deeper" here has to mean bluer rather than darker.
    kind: "floor", id: "floor_pool_deep", name: "Deep Water",
    tile: { w: 64, h: 32 },
    sides: { left: 0x3f5e9e, right: 0x2f8f8f },
  },
  {
    kind: "wall", id: "wall_spa", name: "Spa Tile",
    tile: { w: 16, h: 32 },
    cap: 0xcbc0ac,
  },
  // Penthouse suites (#356).
  {
    kind: "floor", id: "floor_fandeco", name: "Fan Parquet",
    tile: { w: 64, h: 32 },
    sides: { left: 0x656056, right: 0x9c9484 },
  },
  // The one tile in the set that is a whole wall rather than a repeat up it: the cornice, chair
  // rail and skirting only sit where they belong if the motif is 128 tall.
  {
    kind: "wall", id: "wall_decopanel", name: "Deco Panelling",
    tile: { w: 16, h: 128 },
    cap: 0xcbc0ac,
  },
  // Jazz Lounge pack (#358): crimson/gold/charcoal/plum.
  {
    kind: "floor", id: "floor_lounge", name: "Lounge Carpet",
    tile: { w: 64, h: 32 },
    sides: { left: 0xaa3333, right: 0xdd4242 },
  },
  {
    kind: "wall", id: "wall_velvet", name: "Velvet Panelling",
    tile: { w: 16, h: 32 },
    cap: 0xc2a36b,
  },
  // First AI-motif set (#435, the #270 decision). The motif is generated, the repeat is ours:
  // tools/decor/motif.ts samples each motif through a map that is periodic on the tile, and
  // reduces to the ramps named beside each def rather than to all 91. Wider tiles than the hand-
  // authored set, because one generated motif needs the room to read.
  {
    // gold + navy + ivory. A spot wallpaper: one medallion per floor tile of wall.
    kind: "wall", id: "wall_sunburst", name: "Deco Sunburst",
    tile: { w: 32, h: 32 },
    cap: 0xcbc0ac,
  },
  {
    // crimson + sand + ivory. Half the height of the sunburst, so the fans stack into rows.
    kind: "wall", id: "wall_fanshell", name: "Fan Shell",
    tile: { w: 32, h: 16 },
    cap: 0xc2a36b,
  },
  {
    // ivory + sand + slate. The chips are carried onto the diamond lattice like every floor here,
    // so they lie in the ground plane instead of facing the camera.
    kind: "floor", id: "floor_terrazzo", name: "Terrazzo",
    tile: { w: 64, h: 32 },
    sides: { left: 0x656056, right: 0x9c9484 },
  },
  {
    // gold + navy + ivory. One star per diamond — the motif's own square edge becomes the grout.
    kind: "floor", id: "floor_mosaic", name: "Deco Mosaic",
    tile: { w: 64, h: 32 },
    sides: { left: 0x3f5e9e, right: 0x527acd },
  },
];

const FLOOR_IDS = new Set(DECOR_CATALOG.filter((d) => d.kind === "floor").map((d) => d.id));

/** Enough for a zoned public room to name every surface it has, and few enough that the regions can
 *  never be the reason a room_state is big. The Resort Grounds — 200x200, the largest room in the
 *  hotel — spends four. */
export const MAX_DECOR_REGIONS = 32;

/** A floor override on a rectangle of tiles, inclusive at both ends, which is how the room builders
 *  measure their own rect fills (server grounds.ts).
 *
 *  Rectangles rather than a decor id per tile: room_state already carries a 40,000-character
 *  heightmap for the Grounds (#362), and a per-tile map would be the larger half of the message for
 *  a floor that is laid out in zones anyway. The Grounds' four rectangles cost 245 bytes.
 *
 *  The id is checked against the catalog here, unlike the room-wide `floor` below. Regions are
 *  authored by the house in server constants and never by a player, so a strict check is a
 *  boot-time typo catcher with nobody to lock out. */
export const DecorRegionSchema = z
  .object({
    x0: z.number().int().min(0), y0: z.number().int().min(0),
    x1: z.number().int().min(0), y1: z.number().int().min(0),
    floor: z.string().refine((id) => FLOOR_IDS.has(id), "not a floor decor id"),
  })
  .refine((r) => r.x0 <= r.x1 && r.y0 <= r.y1, "rectangle is inside out (x1 < x0, or y1 < y0)");
export type DecorRegion = z.infer<typeof DecorRegionSchema>;

/** What a room hangs and lays. Every side optional: a room with none keeps the default green
 *  checker and plaster the client has always drawn. */
export const RoomDecorSchema = z.object({
  floor: z.string().optional(),
  wall: z.string().optional(),
  /** Floor overrides on top of `floor` (#407), so a zoned room can give its pool, its stage and its
   *  colonnade different surfaces. Later rectangles paint over earlier ones, matching the rect
   *  fills the room builders draw the floor with. Walls stay room-wide. */
  regions: z.array(DecorRegionSchema).max(MAX_DECOR_REGIONS).optional(),
});
export type RoomDecor = z.infer<typeof RoomDecorSchema>;

/** Why a room's decor regions do not fit a `width` x `height` floor, or null when they do. The one
 *  check the wire schema cannot make, because the schema never sees the room it decorates. The
 *  server runs it at seed time so a mistyped rect fails at boot rather than painting off the edge
 *  of a live room. */
export function decorRegionsFault(decor: RoomDecor, width: number, height: number): string | null {
  for (const r of decor.regions ?? []) {
    if (r.x1 < width && r.y1 < height) continue;
    return `decor region ${r.floor} at ${r.x0},${r.y0}..${r.x1},${r.y1} runs past the ` +
      `${width}x${height} floor — the bounds are inclusive, so the last tile is ` +
      `${width - 1},${height - 1}`;
  }
  return null;
}
