import { z } from "zod";
import { WALL_SEG_PX, WALL_TOP_PX } from "./walls.ts";

// Flat decor (#260): wallpapers and floor patterns. The third asset class, and the only one that
// may be raster.
//
// Why raster is safe here and nowhere else: a raster asset carries no DepthBox, so gateDrawOrder
// and gateSeatOcclusion cannot cover it (#233, #235). That only matters for things standing on
// the floor that avatars route around and sit on. A floor pattern IS the floor and a wallpaper IS
// the wall — both are already drawn as the flat backdrop everything else sorts against, so there
// is no ordering left to get wrong.
//
// The asset is one tile, and the client repeats it. Nothing is pre-projected: the tile is authored
// in the surface's own two axes and a texture matrix carries it into screen space, so the same
// bytes serve the left wall, the right wall and every raised floor height.
//
//   floor — the tile is screen-space, axis-aligned. Floor diamonds tessellate on the lattice
//           generated by (+32, +16) and (-32, +16), and a w x h rectangle repeats compatibly with
//           it exactly when w is a multiple of 64 and h a multiple of 32. That is why the cell is
//           two diamonds wide: the existing two-tone checker is the smallest legal pattern.
//   wall  — the tile is wall-space (u along the wall, v straight down), the same axes walls.ts
//           measures hanging items in. The client shears it by the wall's 2:1 axis at draw time.
//
// Colour comes from the same 91 the generator emits, so gatePalette still holds for the class.

export const DECOR_KINDS = ["floor", "wall"] as const;

const TileSchema = z.object({
  w: z.number().int().min(1),
  h: z.number().int().min(1),
});

export const DecorDefSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("floor"),
    id: z.string(),
    name: z.string(),
    tile: TileSchema,
    /** The two vertical faces a raised tile shows (client scene/room.ts). Flat colours, not
     *  raster: the floor tile is authored in the ground plane, and shearing it up a riser would
     *  read as a smear rather than as the same material turned on edge. */
    sides: z.object({ left: z.number().int(), right: z.number().int() }),
  }),
  z.object({
    kind: z.literal("wall"),
    id: z.string(),
    name: z.string(),
    tile: TileSchema,
    /** The wall's own thickness seen from above — the cap strip along the top edge. */
    cap: z.number().int(),
  }),
]);
export type DecorDef = z.infer<typeof DecorDefSchema>;

/** What a room hangs and lays. Both sides optional: a room with neither keeps the default green
 *  checker and plaster the client has always drawn. */
export const RoomDecorSchema = z.object({
  floor: z.string().optional(),
  wall: z.string().optional(),
});
export type RoomDecor = z.infer<typeof RoomDecorSchema>;

/** Screen-space lattice cell of the floor: the bounding box of one tile diamond at scale 64, and
 *  the smallest rectangle that repeats on the diamond lattice. */
export const FLOOR_CELL_W = 64;
export const FLOOR_CELL_H = 32;

/** Why a tile size is illegal for its surface, or null when it is legal. Shared so the gate and
 *  the authoring tool cannot drift apart. */
export function decorTileFault(def: DecorDef): string | null {
  const { w, h } = def.tile;
  if (def.kind === "floor") {
    if (w % FLOOR_CELL_W !== 0 || h % FLOOR_CELL_H !== 0) {
      return `floor tile ${w}x${h} is off the diamond lattice — width must be a multiple of ` +
        `${FLOOR_CELL_W} and height a multiple of ${FLOOR_CELL_H}, or the pattern shifts by half ` +
        `a tile every row`;
    }
    return null;
  }
  if (w % 2 !== 0) {
    return `wall tile width ${w} is odd — the wall's 2:1 axis drops half a screen pixel per ` +
      `along-wall pixel, so an odd repeat lands the pattern half a pixel off itself`;
  }
  if (WALL_SEG_PX % w !== 0) {
    return `wall tile width ${w} does not divide the ${WALL_SEG_PX} px segment — the pattern ` +
      `would be cut mid-motif at every segment boundary`;
  }
  if (WALL_TOP_PX % h !== 0) {
    return `wall tile height ${h} does not divide the ${WALL_TOP_PX} px wall — the pattern would ` +
      `be cut mid-motif at the floor line`;
  }
  return null;
}

export const DECOR_CATALOG: DecorDef[] = [
  {
    kind: "floor", id: "floor_marble", name: "Marble Chequer",
    tile: { w: 64, h: 32 },
    sides: { left: 0x656056, right: 0x768594 },
  },
  {
    kind: "floor", id: "floor_parquet", name: "Parquet",
    tile: { w: 64, h: 32 },
    sides: { left: 0x8b4513, right: 0xb55a19 },
  },
  {
    kind: "floor", id: "floor_planks", name: "Lodge Planks",
    tile: { w: 64, h: 32 },
    sides: { left: 0x8b4513, right: 0xb55a19 },
  },
  {
    kind: "wall", id: "wall_wainscot", name: "Wainscot Panelling",
    tile: { w: 16, h: 128 },
    cap: 0xcbc0ac,
  },
  {
    kind: "wall", id: "wall_logcabin", name: "Log Cabin",
    tile: { w: 32, h: 32 },
    cap: 0xcbc0ac,
  },
  {
    kind: "wall", id: "wall_pinstripe", name: "Casino Pinstripe",
    tile: { w: 16, h: 32 },
    cap: 0x8d9eb1,
  },
  // Jazz Lounge pack (#358): crimson/gold/charcoal/plum.
  {
    kind: "floor", id: "floor_lounge", name: "Lounge Carpet",
    tile: { w: 64, h: 32 },
    sides: { left: 0xaa3333, right: 0xdd4242 },
  },
  {
    kind: "wall", id: "wall_velvet", name: "Velvet Panelling",
    tile: { w: 16, h: 32 },
    cap: 0xc2a36b,
  },
];
