import type { FurniDef, WallDef } from "./protocol.ts";

// seatHeight is the seat surface read off the authored geometry, not guessed: the box-path defs
// come from archetypes.ts slot boxes, the 3D-assisted ones from the rig.py primitive that forms
// the seat. It is always below stackHeights[0], which is the silhouette top.
export const PROTOTYPE_CATALOG: FurniDef[] = [
  { id: "chair_basic", name: "Chair",  theme: "starter", w: 1, l: 1, stackHeights: [1.0],  canWalk: false, canStackOn: false, seatHeight: 0.65625, color: 0xb5651d },
  { id: "table_basic", name: "Table",  theme: "starter", w: 2, l: 1, stackHeights: [1.0],  canWalk: false, canStackOn: true,  seatHeight: null,    color: 0x8b4513 },
  { id: "sofa_basic",  name: "Sofa",   theme: "starter", w: 2, l: 1, stackHeights: [1.0],  canWalk: false, canStackOn: false, seatHeight: 0.5625,  color: 0x7a3e9d },
  { id: "plant_basic", name: "Plant",  theme: "starter", w: 1, l: 1, stackHeights: [2.0],  canWalk: false, canStackOn: false, seatHeight: null,    color: 0x2e8b57 },
  { id: "rug_basic",   name: "Rug",    theme: "starter", w: 3, l: 2, stackHeights: [0.05], canWalk: true,  canStackOn: true,  seatHeight: null,    color: 0xaa3333 },
  // 3D-assisted path (#202): frozen bundles in tools/artgen/frozen, merged by the generator CLI.
  // stackHeights[0] = drawn height rounded up to a whole z-pixel (1/32).
  { id: "casino_table",  name: "Casino Table", theme: "casino", w: 2, l: 2, stackHeights: [1.4375],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "casino_stool",  name: "Casino Stool", theme: "casino", w: 1, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.82, color: 0xaa3333 },
  { id: "cafe_table",    name: "Café Table",   theme: "cafe", w: 1, l: 1, stackHeights: [1.03125], canWalk: false, canStackOn: true,  seatHeight: null, color: 0xcfc7b6 },
  { id: "cafe_chair",    name: "Café Chair",   theme: "cafe", w: 1, l: 1, stackHeights: [1.25],    canWalk: false, canStackOn: false, seatHeight: 0.58, color: 0x2f8f8f },
  { id: "bed_basic",     name: "Bed",          theme: "bedroom", w: 2, l: 3, stackHeights: [0.96875], canWalk: false, canStackOn: false, seatHeight: 0.55, color: 0x3f5e9e },
  // A lit lamp is the same size as an unlit one, but placement reads stackHeights[state] and
  // throws on a state it has no height for — so every toggle def declares both (#326).
  { id: "lamp_basic",    name: "Lamp",         theme: "bedroom", w: 1, l: 1, stackHeights: [2.21875, 2.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520, interaction: "toggle" },
  // Free (#347): a book is a prop, not a sink. It runs the vend rail so the shelf behaves like
  // every other counter — walk up, use it, carry the thing for two minutes.
  { id: "shelf_basic",   name: "Shelf",        theme: "bedroom", w: 2, l: 1, stackHeights: [1.90625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xb5651d, interaction: "read", vend: { item: "book", price: 0 } },
  { id: "divider_basic", name: "Divider",      theme: "bedroom", w: 2, l: 1, stackHeights: [1.0625],  canWalk: false, canStackOn: true,  seatHeight: null, color: 0x5b6672 },
  // Switched on and off like the lamp (#331), and like the lamp the state is all client-side — the
  // frozen bundle has one frame per facing, so nothing here needs re-rendering.
  { id: "stereo_basic",  name: "Stereo",       theme: "bedroom", w: 1, l: 1, stackHeights: [1.375, 1.375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55, interaction: "toggle" },
  { id: "slot_machine",   name: "Slot Machine",   theme: "casino", w: 1, l: 1, stackHeights: [2],       canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  // The casino-side drink (#347): the bar shakes cocktails at 2 Stars, the café pours coffee at 1.
  { id: "bar_counter",    name: "Bar Counter",    theme: "casino", w: 2, l: 1, stackHeights: [1.1875],  canWalk: false, canStackOn: true,  seatHeight: null, color: 0xb5651d, interaction: "vend", vend: { item: "drink_cocktail", price: 2 } },
  { id: "arcade_cabinet", name: "Arcade Cabinet", theme: "casino", w: 1, l: 1, stackHeights: [1.875],   canWalk: false, canStackOn: false, seatHeight: null, color: 0x3f5e9e },
  // Wishing, not washing (#347): the basin is where you scrub, the fountain is where the Star goes.
  { id: "fountain",       name: "Fountain",       theme: "casino", w: 2, l: 2, stackHeights: [1.6875],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f, interaction: "wish" },
  // Lodge set (#314): soft furniture, a hearth, greenery and a divider that is not a wall.
  { id: "armchair_lounge", name: "Lodge Armchair", theme: "lodge", w: 1, l: 1, stackHeights: [1.75],    canWalk: false, canStackOn: false, seatHeight: 1,    color: 0xaa3333 },
  { id: "sofa_lodge",      name: "Lodge Sofa",     theme: "lodge", w: 2, l: 1, stackHeights: [2],       canWalk: false, canStackOn: false, seatHeight: 1,    color: 0x2e8b57 },
  { id: "table_round",     name: "Round Table",    theme: "lodge", w: 1, l: 1, stackHeights: [1.5],     canWalk: false, canStackOn: true,  seatHeight: null, color: 0xb5651d },
  { id: "plant_fern",      name: "Potted Fern",    theme: "lodge", w: 1, l: 1, stackHeights: [1.53125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  // Lit and unlit (#331). The mesh already carries flames in the firebox, so the switch is the
  // firelight and the smoke off them rather than a second set of frames.
  { id: "fireplace",       name: "Fireplace",      theme: "lodge", w: 2, l: 1, stackHeights: [2.5, 2.5], canWalk: false, canStackOn: false, seatHeight: null, color: 0x5b6672, interaction: "toggle" },
  { id: "railing",         name: "Railing",        theme: "lodge", w: 1, l: 1, stackHeights: [1],       canWalk: false, canStackOn: false, seatHeight: null, color: 0xb5651d },
  // Lodge round 2 (#323): the floor half of the wall-clutter pass. rug_lodge is the only walkable
  // 3D-assisted part — canWalk puts it on the client's floor_furni layer, under every avatar.
  { id: "rug_lodge",   name: "Lodge Rug", theme: "lodge", w: 2, l: 2, stackHeights: [0.0625],  canWalk: true,  canStackOn: true,  seatHeight: null, color: 0xaa3333 },
  { id: "stool_lodge", name: "Lodge Stool", theme: "lodge", w: 1, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.82, color: 0xb5651d },
  { id: "side_table",  name: "Side Table",  theme: "lodge", w: 1, l: 1, stackHeights: [0.75],    canWalk: false, canStackOn: true,  seatHeight: null, color: 0xb5651d },
  // Amenities (#327): the two fixtures a café and a washroom need that no archetype covered.
  { id: "vending_machine", name: "Vending Machine", theme: "cafe", w: 1, l: 1, stackHeights: [2],       canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f, interaction: "vend", vend: { item: "drink_cola", price: 1 } },
  { id: "sink_basic",      name: "Wash Basin",      theme: "cafe", w: 1, l: 1, stackHeights: [1],       canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484, interaction: "wash" },
  // Pool & spa deck (#357): the resort half of a casino resort, which the catalog had none of.
  // Nothing here stacks. The parasol's stack top is the canopy at 2.5 and the trolley's is a hand
  // above its own bottles — canStackOn would put a lamp on top of an umbrella.
  { id: "sun_lounger",   name: "Sun Lounger",   theme: "pool", w: 1, l: 2, stackHeights: [1.1875],  canWalk: false, canStackOn: false, seatHeight: 0.58, color: 0x2f8f8f },
  { id: "deck_chair",    name: "Deck Chair",    theme: "pool", w: 1, l: 1, stackHeights: [1.5625],  canWalk: false, canStackOn: false, seatHeight: 0.62, color: 0x2f8f8f },
  { id: "parasol_table", name: "Parasol Table", theme: "pool", w: 2, l: 2, stackHeights: [2.5],     canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "cabana",        name: "Cabana",        theme: "pool", w: 2, l: 2, stackHeights: [2.5],     canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  // `wash` off the def (#347): the rail broadcasts the action and the client plays the splash, so
  // a tub reuses the basin's verb and needs no server code of its own.
  { id: "hot_tub",       name: "Hot Tub",       theme: "pool", w: 2, l: 2, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f, interaction: "wash" },
  { id: "towel_rack",    name: "Towel Rack",    theme: "pool", w: 1, l: 1, stackHeights: [1.4375],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "potted_palm",   name: "Potted Palm",   theme: "pool", w: 1, l: 1, stackHeights: [1.875],   canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "drinks_trolley", name: "Drinks Trolley", theme: "pool", w: 1, l: 1, stackHeights: [1.375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484 },
  { id: "pool_ladder",   name: "Pool Ladder",   theme: "pool", w: 1, l: 1, stackHeights: [1.25],    canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484 },
  // Prestige fixtures (#210): account-bound, flagship-priced, never tradeable. Deliberately their
  // own meshes rather than recolours — a fixture at 5.5× the daily ceiling has to read as one.
  { id: "billiards_table",      name: "Billiards Table", theme: "prestige", w: 3, l: 2, stackHeights: [1.09375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "penthouse_candelabra", name: "Candelabra",  theme: "prestige", w: 1, l: 1, stackHeights: [2.34375, 2.34375], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520, interaction: "toggle" },
  { id: "stage_platform", name: "Stage Platform", theme: "lounge", w: 2, l: 2, stackHeights: [0.25], canWalk: true, canStackOn: true, seatHeight: null, color: 0x7a3e9d },
  { id: "grand_piano", name: "Grand Piano", theme: "lounge", w: 2, l: 2, stackHeights: [1.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "double_bass", name: "Double Bass", theme: "lounge", w: 1, l: 1, stackHeights: [2.375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "drum_kit", name: "Drum Kit", theme: "lounge", w: 2, l: 2, stackHeights: [1.46875], canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "mic_stand", name: "Mic Stand", theme: "lounge", w: 1, l: 1, stackHeights: [2.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x5b6672 },
  { id: "speaker_column", name: "Speaker Column", theme: "lounge", w: 1, l: 1, stackHeights: [2.40625, 2.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55, interaction: "toggle" },
  { id: "velvet_booth", name: "Velvet Booth", theme: "lounge", w: 2, l: 1, stackHeights: [2.1875], canWalk: false, canStackOn: false, seatHeight: 0.96, color: 0xaa3333 },
  { id: "cocktail_table", name: "Cocktail Table", theme: "lounge", w: 1, l: 1, stackHeights: [1.34375], canWalk: false, canStackOn: true, seatHeight: null, color: 0x4a4d55 },
  { id: "stage_light", name: "Stage Light", theme: "lounge", w: 1, l: 1, stackHeights: [1.75, 1.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55, interaction: "toggle" },
  // Grand Wheel (#429): the casino's landmark, at 3.625 the tallest thing in the catalog and half
  // an avatar above the next tallest. Four states, one per quarter of the spin — the client cycles
  // 0→1→2→3 while the wheel runs. Every state is the same height, because a spinning wheel is not
  // a taller one and placement.ts throws on a state it has no height for (the lamp_basic rule).
  { id: "grand_wheel",  name: "Grand Wheel", theme: "casino", w: 2, l: 1, stackHeights: [3.625, 3.625, 3.625, 3.625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333, interaction: "wheel" },
  { id: "wheel_podium", name: "Odds Board",  theme: "casino", w: 1, l: 1, stackHeights: [1.9375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  // Blackjack (#428). Same 2x2 as casino_table and deliberately not the same object: the deep
  // apron, the ivory rail and the dealer's tray on the north edge are what say which game it is.
  { id: "blackjack_table", name: "Blackjack Table", theme: "casino", w: 2, l: 2, stackHeights: [1.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57, interaction: "blackjack" },
  // Colorways (#229): the same authored mesh with its ramps remapped, so they share their base's
  // geometry exactly — heights and seat surfaces are identical and the gates check that.
  { id: "cafe_chair_crimson",  name: "Crimson Café Chair", theme: "cafe", w: 1, l: 1, stackHeights: [1.25],    canWalk: false, canStackOn: false, seatHeight: 0.58, color: 0xaa3333 },
  { id: "cafe_chair_navy",     name: "Navy Café Chair", theme: "cafe", w: 1, l: 1, stackHeights: [1.25],    canWalk: false, canStackOn: false, seatHeight: 0.58, color: 0x3f5e9e },
  { id: "casino_stool_fern",   name: "Baize Stool", theme: "casino", w: 1, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.82, color: 0x2e8b57 },
  { id: "divider_basic_plum",  name: "Plum Divider", theme: "bedroom", w: 2, l: 1, stackHeights: [1.0625],  canWalk: false, canStackOn: true,  seatHeight: null, color: 0x7a3e9d },
  { id: "armchair_lounge_navy", name: "Navy Lodge Armchair", theme: "lodge", w: 1, l: 1, stackHeights: [1.75],    canWalk: false, canStackOn: false, seatHeight: 1,    color: 0x3f5e9e },
  { id: "armchair_lounge_fern", name: "Fern Lodge Armchair", theme: "lodge", w: 1, l: 1, stackHeights: [1.75],    canWalk: false, canStackOn: false, seatHeight: 1,    color: 0x2e8b57 },
  { id: "sofa_lodge_plum",      name: "Plum Lodge Sofa",     theme: "lodge", w: 2, l: 1, stackHeights: [2],       canWalk: false, canStackOn: false, seatHeight: 1,    color: 0x7a3e9d },
  { id: "table_round_onyx",     name: "Onyx Round Table",    theme: "lodge", w: 1, l: 1, stackHeights: [1.5],     canWalk: false, canStackOn: true,  seatHeight: null, color: 0x4a4d55 },
  { id: "plant_fern_exotic",    name: "Exotic Fern",         theme: "lodge", w: 1, l: 1, stackHeights: [1.53125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x7a3e9d },
  { id: "fireplace_stone",      name: "Sandstone Hearth",    theme: "lodge", w: 2, l: 1, stackHeights: [2.5, 2.5], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b, interaction: "toggle" },
  { id: "railing_iron",         name: "Iron Railing",        theme: "lodge", w: 1, l: 1, stackHeights: [1],       canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "stool_lodge_charcoal", name: "Charcoal Lodge Stool", theme: "lodge", w: 1, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.82, color: 0x4a4d55 },
  { id: "side_table_slate",     name: "Slate Side Table",     theme: "lodge", w: 1, l: 1, stackHeights: [0.75],    canWalk: false, canStackOn: true,  seatHeight: null, color: 0x5b6672 },
  { id: "cafe_counter",         name: "Café Counter",         theme: "cafe", w: 2, l: 1, stackHeights: [1.1875],  canWalk: false, canStackOn: true,  seatHeight: null, color: 0x2f8f8f, interaction: "vend", vend: { item: "drink_coffee", price: 1 } },
  // Pool & spa deck colorways (#357).
  { id: "sun_lounger_crimson",   name: "Crimson Sun Lounger",   theme: "pool", w: 1, l: 2, stackHeights: [1.1875],  canWalk: false, canStackOn: false, seatHeight: 0.58, color: 0xaa3333 },
  { id: "deck_chair_crimson",    name: "Crimson Deck Chair",    theme: "pool", w: 1, l: 1, stackHeights: [1.5625],  canWalk: false, canStackOn: false, seatHeight: 0.62, color: 0xaa3333 },
  { id: "deck_chair_navy",       name: "Navy Deck Chair",       theme: "pool", w: 1, l: 1, stackHeights: [1.5625],  canWalk: false, canStackOn: false, seatHeight: 0.62, color: 0x3f5e9e },
  { id: "parasol_table_teal",    name: "Teal Parasol Table",    theme: "pool", w: 2, l: 2, stackHeights: [2.5],     canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "cabana_crimson",        name: "Crimson Cabana",        theme: "pool", w: 2, l: 2, stackHeights: [2.5],     canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "hot_tub_cedar",         name: "Cedar Hot Tub",         theme: "pool", w: 2, l: 2, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b, interaction: "wash" },
  { id: "towel_rack_linen",      name: "Linen Towel Rack",      theme: "pool", w: 1, l: 1, stackHeights: [1.4375],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x3f5e9e },
  { id: "potted_palm_teal",      name: "Teal Potted Palm",      theme: "pool", w: 1, l: 1, stackHeights: [1.875],   canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "drinks_trolley_sunset", name: "Sunset Drinks Trolley", theme: "pool", w: 1, l: 1, stackHeights: [1.375],   canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "bar_counter_pool",      name: "Pool Bar",              theme: "pool", w: 2, l: 1, stackHeights: [1.1875],  canWalk: false, canStackOn: true,  seatHeight: null, color: 0xc2a36b, interaction: "vend", vend: { item: "drink_cocktail", price: 2 } },
  // Penthouse suites (#356): the art-deco set for The Grand's suites. Navy and charcoal carcases,
  // gold trim, ivory upholstery — four ramps that differ in hue, so the trim reads on every body
  // the colorways below reach for.
  { id: "bed_grand",       name: "Grand Bed",       theme: "penthouse", w: 2, l: 2, stackHeights: [1.5625],  canWalk: false, canStackOn: false, seatHeight: 0.82, color: 0x3f5e9e },
  // Not stackable, unlike the dresser: stacking lands at stackHeights[0], which on a vanity is the
  // top of the mirror rather than the top of the table.
  { id: "vanity_deco",     name: "Deco Vanity",     theme: "penthouse", w: 2, l: 1, stackHeights: [1.96875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x3f5e9e },
  { id: "chaise_deco",     name: "Deco Chaise",     theme: "penthouse", w: 2, l: 1, stackHeights: [1.1875],  canWalk: false, canStackOn: false, seatHeight: 0.76, color: 0x3f5e9e },
  { id: "armoire_deco",    name: "Deco Armoire",    theme: "penthouse", w: 2, l: 1, stackHeights: [2.5625],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "barcart_deco",    name: "Bar Cart",        theme: "penthouse", w: 1, l: 1, stackHeights: [1.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "screen_deco",     name: "Folding Screen",  theme: "penthouse", w: 2, l: 1, stackHeights: [2.0625],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x3f5e9e },
  { id: "mirror_standing", name: "Cheval Mirror",   theme: "penthouse", w: 1, l: 1, stackHeights: [1.8125],  canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "ottoman_deco",    name: "Deco Ottoman",    theme: "penthouse", w: 1, l: 1, stackHeights: [0.75],    canWalk: false, canStackOn: false, seatHeight: 0.74, color: 0x3f5e9e },
  { id: "dresser_deco",    name: "Deco Dresser",    theme: "penthouse", w: 2, l: 1, stackHeights: [1.125],   canWalk: false, canStackOn: true,  seatHeight: null, color: 0x4a4d55 },
  // A bulb on a stand, so the client's default Glow already describes it — the toggle costs the
  // second stackHeights entry (#326) and nothing else.
  { id: "lamp_deco",       name: "Deco Floor Lamp", theme: "penthouse", w: 1, l: 1, stackHeights: [2.25, 2.25], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520, interaction: "toggle" },
  { id: "bed_grand_plum",       name: "Plum Grand Bed",     theme: "penthouse", w: 2, l: 2, stackHeights: [1.5625],  canWalk: false, canStackOn: false, seatHeight: 0.82, color: 0x7a3e9d },
  { id: "chaise_deco_crimson",  name: "Crimson Chaise",     theme: "penthouse", w: 2, l: 1, stackHeights: [1.1875],  canWalk: false, canStackOn: false, seatHeight: 0.76, color: 0xaa3333 },
  { id: "screen_deco_jade",     name: "Jade Screen",        theme: "penthouse", w: 2, l: 1, stackHeights: [2.0625],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "dresser_deco_navy",    name: "Navy Deco Dresser",  theme: "penthouse", w: 2, l: 1, stackHeights: [1.125],   canWalk: false, canStackOn: true,  seatHeight: null, color: 0x3f5e9e },
  { id: "ottoman_deco_ivory",   name: "Ivory Deco Ottoman", theme: "penthouse", w: 1, l: 1, stackHeights: [0.75],    canWalk: false, canStackOn: false, seatHeight: 0.74, color: 0x9c9484 },
  { id: "armoire_deco_ivory",   name: "Ivory Deco Armoire", theme: "penthouse", w: 2, l: 1, stackHeights: [2.5625],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484 },
  { id: "mirror_standing_plum", name: "Plum Cheval Mirror", theme: "penthouse", w: 1, l: 1, stackHeights: [1.8125],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x7a3e9d },
  { id: "stage_platform_parquet", name: "Parquet Stage", theme: "lounge", w: 2, l: 2, stackHeights: [0.25], canWalk: true, canStackOn: true, seatHeight: null, color: 0xc2a36b },
  { id: "grand_piano_oak", name: "Oak Grand", theme: "lounge", w: 2, l: 2, stackHeights: [1.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "double_bass_ebony", name: "Ebony Double Bass", theme: "lounge", w: 1, l: 1, stackHeights: [2.375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "speaker_column_vintage", name: "Vintage Speaker Column", theme: "lounge", w: 1, l: 1, stackHeights: [2.40625, 2.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xb5651d, interaction: "toggle" },
  { id: "velvet_booth_plum", name: "Plum Velvet Booth", theme: "lounge", w: 2, l: 1, stackHeights: [2.1875], canWalk: false, canStackOn: false, seatHeight: 0.96, color: 0x7a3e9d },
  { id: "velvet_booth_charcoal", name: "Charcoal Velvet Booth", theme: "lounge", w: 2, l: 1, stackHeights: [2.1875], canWalk: false, canStackOn: false, seatHeight: 0.96, color: 0x4a4d55 },
  { id: "cocktail_table_walnut", name: "Walnut Cocktail Table", theme: "lounge", w: 1, l: 1, stackHeights: [1.34375], canWalk: false, canStackOn: true, seatHeight: null, color: 0xb5651d },
  { id: "stage_light_plum", name: "Plum Stage Light", theme: "lounge", w: 1, l: 1, stackHeights: [1.75, 1.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x7a3e9d, interaction: "toggle" },
  // Luck Lever exclusives (#210): won, never sold, so they carry no catalog price.
  { id: "arcade_cabinet_plum", name: "Plum Arcade Cabinet", theme: "casino", w: 1, l: 1, stackHeights: [1.875],   canWalk: false, canStackOn: false, seatHeight: null, color: 0x7a3e9d },
  { id: "fountain_gilded",     name: "Gilded Fountain",     theme: "casino", w: 2, l: 2, stackHeights: [1.6875],  canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520, interaction: "wish" },
  // Collection-set rewards (#210): minted account-bound on completion, obtainable no other way.
  { id: "cafe_table_marble",   name: "Marble Café Table",   theme: "cafe", w: 1, l: 1, stackHeights: [1.03125], canWalk: false, canStackOn: true,  seatHeight: null, color: 0x5b6672 },
  { id: "casino_table_onyx",   name: "Onyx Casino Table",   theme: "casino", w: 2, l: 2, stackHeights: [1.4375],  canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  // Bannerhold pilots (blitz task 5): one base, one colorway, one wall — the proof the art budget
  // holds before bulk authoring. stackHeights/seatHeight and span/plane/mount read off the render
  // by tools/artgen/postpass.ts. The dusk colorway is the same mesh, oak remapped to slate.
  // Wave A1 (blitz task 6): starter, cafe, bedroom — 23 bases + 16 walls.
  { id: "starter_armchair", name: "Starter Armchair", theme: "starter", w: 1, l: 1, stackHeights: [0.9375], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0xc2a36b },
  { id: "starter_coffee_table", name: "Starter Coffee Table", theme: "starter", w: 1, l: 1, stackHeights: [0.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "starter_entry_mat", name: "Starter Entry Mat", theme: "starter", w: 1, l: 1, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xaa3333 },
  { id: "starter_floor_lamp", name: "Starter Floor Lamp", theme: "starter", w: 1, l: 1, stackHeights: [1.625, 1.625], canWalk: false, canStackOn: false, seatHeight: null, interaction: "toggle", color: 0xdaa520 },
  { id: "starter_bookcase", name: "Starter Bookcase", theme: "starter", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "cafe_espresso_machine", name: "Espresso Machine", theme: "cafe", w: 1, l: 1, stackHeights: [1], canWalk: false, canStackOn: false, seatHeight: null, interaction: "vend", vend: { item: "drink_coffee", price: 1 }, color: 0x4a4d55 },
  { id: "cafe_bakery_island", name: "Bakery Island", theme: "cafe", w: 2, l: 1, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "cafe_bistro_table", name: "Bistro Table", theme: "cafe", w: 1, l: 1, stackHeights: [0.78125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "cafe_bistro_chair", name: "Bistro Chair", theme: "cafe", w: 1, l: 1, stackHeights: [1], canWalk: false, canStackOn: false, seatHeight: 0.52, color: 0x2f8f8f },
  { id: "cafe_pastry_case", name: "Pastry Case", theme: "cafe", w: 1, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "cafe_barista_stool", name: "Barista Stool", theme: "cafe", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: 0.7, color: 0xaa3333 },
  { id: "cafe_potted_herb", name: "Potted Herb", theme: "cafe", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "cafe_woven_rug", name: "Woven Rug", theme: "cafe", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xc2a36b },
  { id: "bedroom_bed_frame", name: "Bed Frame", theme: "bedroom", w: 1, l: 2, stackHeights: [0.90625], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0x3f5e9e },
  { id: "bedroom_dresser", name: "Dresser", theme: "bedroom", w: 1, l: 1, stackHeights: [0.90625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "bedroom_nightstand", name: "Nightstand", theme: "bedroom", w: 1, l: 1, stackHeights: [0.5], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "bedroom_wardrobe", name: "Wardrobe", theme: "bedroom", w: 2, l: 1, stackHeights: [2.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "bedroom_vanity", name: "Vanity", theme: "bedroom", w: 1, l: 1, stackHeights: [1.3125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "bedroom_rug", name: "Bedroom Rug", theme: "bedroom", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x7a3e9d },
  { id: "bedroom_table_lamp", name: "Table Lamp", theme: "bedroom", w: 1, l: 1, stackHeights: [0.875, 0.875], canWalk: false, canStackOn: false, seatHeight: null, interaction: "toggle", color: 0xdaa520 },
  { id: "bedroom_bench", name: "Bedroom Bench", theme: "bedroom", w: 1, l: 1, stackHeights: [0.46875], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0x7a3e9d },
  { id: "bedroom_reading_chair", name: "Reading Chair", theme: "bedroom", w: 1, l: 1, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: 0.44, color: 0x7a3e9d },
  { id: "bedroom_desk", name: "Desk", theme: "bedroom", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  // Wave A2 colorways (blitz task 7).
  { id: "casino_card_table_emerald", name: "Emerald Card Table", theme: "casino", w: 2, l: 2, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "casino_dice_table_noir", name: "Noir Dice Table", theme: "casino", w: 2, l: 2, stackHeights: [1.25], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "casino_chip_rack_gold", name: "Gold Chip Rack", theme: "casino", w: 1, l: 1, stackHeights: [0.78125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "casino_dealer_chair_oxblood", name: "Oxblood Dealer Chair", theme: "casino", w: 1, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: 0.68, color: 0x7a1f1f },
  { id: "casino_velvet_rope_crimson", name: "Crimson Velvet Rope", theme: "casino", w: 1, l: 1, stackHeights: [0.9375], canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "casino_round_rug_onyx", name: "Onyx Round Rug", theme: "casino", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x4a4d55 },
  { id: "casino_pendant_lamp_brass", name: "Brass Pendant Lamp", theme: "casino", w: 1, l: 1, stackHeights: [1.71875, 1.71875], canWalk: false, canStackOn: false, seatHeight: null, interaction: "toggle", color: 0xc2a36b },
  // Wave A2 (blitz task 7): casino bases.
  { id: "casino_card_table", name: "Casino Card Table", theme: "casino", w: 2, l: 2, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "casino_dice_table", name: "Casino Dice Table", theme: "casino", w: 2, l: 2, stackHeights: [1.25], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "casino_chip_rack", name: "Chip Rack", theme: "casino", w: 1, l: 1, stackHeights: [0.78125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "casino_dealer_chair", name: "Dealer Chair", theme: "casino", w: 1, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: 0.68, color: 0xaa3333 },
  { id: "casino_velvet_rope", name: "Velvet Rope", theme: "casino", w: 1, l: 1, stackHeights: [0.9375], canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "casino_round_rug", name: "Casino Round Rug", theme: "casino", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xaa3333 },
  { id: "casino_pendant_lamp", name: "Pendant Lamp", theme: "casino", w: 1, l: 1, stackHeights: [1.71875, 1.71875], canWalk: false, canStackOn: false, seatHeight: null, interaction: "toggle", color: 0xdaa520 },
  { id: "casino_banquette", name: "Banquette", theme: "casino", w: 2, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: 0.4, color: 0xaa3333 },
  // Wave A3 colorways (blitz task 8).
  { id: "lodge_wood_stove_slate", name: "Slate Wood Stove", theme: "lodge", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x5b6672 },
  { id: "lodge_log_bed_pine", name: "Pine Log Bed", theme: "lodge", w: 1, l: 2, stackHeights: [0.90625], canWalk: false, canStackOn: false, seatHeight: 0.44, color: 0x2e8b57 },
  { id: "lodge_antler_chair_russet", name: "Russet Antler Chair", theme: "lodge", w: 1, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: 0.4, color: 0xb5651d },
  { id: "lodge_wood_table_cedar", name: "Cedar Wood Table", theme: "lodge", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b },
  { id: "lodge_fur_rug_grey", name: "Grey Fur Rug", theme: "lodge", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x5b6672 },
  { id: "lodge_lantern_copper", name: "Copper Lantern", theme: "lodge", w: 1, l: 1, stackHeights: [0.625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b },
  { id: "pool_hanging_chair_coral", name: "Coral Hanging Chair", theme: "pool", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: 0.86, color: 0xaa3333 },
  { id: "pool_side_table_teal", name: "Teal Side Table", theme: "pool", w: 1, l: 1, stackHeights: [0.59375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "pool_float_rack_sunny", name: "Sunny Float Rack", theme: "pool", w: 1, l: 1, stackHeights: [0.8125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "pool_towel_cart_white", name: "White Towel Cart", theme: "pool", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0xcbc0ac },
  { id: "pool_mosaic_rug_lagoon", name: "Lagoon Mosaic Rug", theme: "pool", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x3f5e9e },
  { id: "pool_shade_sail", name: "Shade Sail", theme: "pool", w: 1, l: 1, stackHeights: [1.28125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "pool_shade_sail_aqua", name: "Aqua Shade Sail", theme: "pool", w: 1, l: 1, stackHeights: [1.28125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  // Wave A4 colorways (blitz task 9).
  { id: "penthouse_sofa_ivory", name: "Ivory Penthouse Sofa", theme: "penthouse", w: 2, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0xcbc0ac },
  { id: "penthouse_marble_table_noir", name: "Noir Marble Table", theme: "penthouse", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "penthouse_dining_chair_champagne", name: "Champagne Dining Chair", theme: "penthouse", w: 1, l: 1, stackHeights: [1], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0xc2a36b },
  { id: "penthouse_bar_midnight", name: "Midnight Penthouse Bar", theme: "penthouse", w: 2, l: 1, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x3f5e9e },
  { id: "penthouse_silk_rug_pearl", name: "Pearl Silk Rug", theme: "penthouse", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xcbc0ac },
  { id: "penthouse_telescope_copper", name: "Copper Telescope", theme: "penthouse", w: 1, l: 1, stackHeights: [1.3125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b },
  { id: "lounge_vibraphone_ivory", name: "Ivory Vibraphone", theme: "lounge", w: 2, l: 1, stackHeights: [0.8125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xcbc0ac },
  { id: "lounge_velvet_sofa_berry", name: "Berry Velvet Sofa", theme: "lounge", w: 2, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0xaa3333 },
  { id: "lounge_record_console_smoke", name: "Smoke Record Console", theme: "lounge", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x5b6672 },
  { id: "lounge_bar_stool_brass", name: "Brass Bar Stool", theme: "lounge", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: 0.7, color: 0xc2a36b },
  { id: "lounge_floor_lamp_amber", name: "Amber Floor Lamp", theme: "lounge", w: 1, l: 1, stackHeights: [1.5625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b },
  { id: "lounge_stage_rug_noir", name: "Noir Stage Rug", theme: "lounge", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x4a4d55 },
  { id: "prestige_gold_throne_onyx", name: "Onyx Gold Throne", theme: "prestige", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0x4a4d55 },
  { id: "prestige_marble_fountain_moonstone", name: "Moonstone Fountain", theme: "prestige", w: 2, l: 2, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8d9eb1 },
  { id: "prestige_crystal_screen_amber", name: "Amber Crystal Screen", theme: "prestige", w: 2, l: 1, stackHeights: [1.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xc2a36b },
  // Wave A4 (blitz task 9): penthouse + lounge + prestige bases.
  { id: "penthouse_sofa", name: "Penthouse Sofa", theme: "penthouse", w: 2, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0xcbc0ac },
  { id: "penthouse_marble_table", name: "Marble Table", theme: "penthouse", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: null, color: 0xcbc0ac },
  { id: "penthouse_dining_chair", name: "Dining Chair", theme: "penthouse", w: 1, l: 1, stackHeights: [1], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0xdaa520 },
  { id: "penthouse_bar", name: "Penthouse Bar", theme: "penthouse", w: 2, l: 1, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "penthouse_silk_rug", name: "Silk Rug", theme: "penthouse", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xcbc0ac },
  { id: "penthouse_telescope", name: "Telescope", theme: "penthouse", w: 1, l: 1, stackHeights: [1.3125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "lounge_vibraphone", name: "Vibraphone", theme: "lounge", w: 2, l: 1, stackHeights: [0.8125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "lounge_velvet_sofa", name: "Velvet Sofa", theme: "lounge", w: 2, l: 1, stackHeights: [0.84375], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0x3f5e9e },
  { id: "lounge_record_console", name: "Record Console", theme: "lounge", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "lounge_bar_stool", name: "Bar Stool", theme: "lounge", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: 0.7, color: 0x4a4d55 },
  { id: "lounge_floor_lamp", name: "Floor Lamp", theme: "lounge", w: 1, l: 1, stackHeights: [1.5625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "lounge_stage_rug", name: "Stage Rug", theme: "lounge", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x3f5e9e },
  { id: "prestige_gold_throne", name: "Gold Throne", theme: "prestige", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0xdaa520 },
  { id: "prestige_marble_fountain", name: "Marble Fountain", theme: "prestige", w: 2, l: 2, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xcbc0ac },
  { id: "prestige_crystal_screen", name: "Crystal Screen", theme: "prestige", w: 2, l: 1, stackHeights: [1.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x5b6672 },
  { id: "prestige_obsidian_table", name: "Obsidian Table", theme: "prestige", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "prestige_velvet_daybed", name: "Velvet Daybed", theme: "prestige", w: 2, l: 1, stackHeights: [0.8125], canWalk: false, canStackOn: false, seatHeight: 0.4, color: 0xaa3333 },
  // Wave A3 (blitz task 8): lodge + pool bases.
  { id: "lodge_wood_stove", name: "Wood Stove", theme: "lodge", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x4a4d55 },
  { id: "lodge_log_bed", name: "Log Bed", theme: "lodge", w: 1, l: 2, stackHeights: [0.90625], canWalk: false, canStackOn: false, seatHeight: 0.44, color: 0x8b4513 },
  { id: "lodge_antler_chair", name: "Antler Chair", theme: "lodge", w: 1, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: 0.4, color: 0xc2a36b },
  { id: "lodge_wood_table", name: "Wood Table", theme: "lodge", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "lodge_fur_rug", name: "Fur Rug", theme: "lodge", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xc2a36b },
  { id: "lodge_lantern", name: "Lantern", theme: "lodge", w: 1, l: 1, stackHeights: [0.625], canWalk: false, canStackOn: false, seatHeight: null, color: 0xdaa520 },
  { id: "lodge_bench", name: "Lodge Bench", theme: "lodge", w: 1, l: 1, stackHeights: [0.46875], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0x8b4513 },
  { id: "pool_hanging_chair", name: "Hanging Chair", theme: "pool", w: 1, l: 1, stackHeights: [1.625], canWalk: false, canStackOn: false, seatHeight: 0.86, color: 0x2f8f8f },
  { id: "pool_side_table", name: "Side Table", theme: "pool", w: 1, l: 1, stackHeights: [0.59375], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "pool_float_rack", name: "Float Rack", theme: "pool", w: 1, l: 1, stackHeights: [0.8125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2f8f8f },
  { id: "pool_towel_cart", name: "Towel Cart", theme: "pool", w: 1, l: 1, stackHeights: [0.75], canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484 },
  { id: "pool_mosaic_rug", name: "Mosaic Rug", theme: "pool", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x2f8f8f },
  { id: "bannerhold_oak_bench", name: "Bannerhold Oak Bench", theme: "bannerhold", w: 2, l: 1, stackHeights: [0.5625], canWalk: false, canStackOn: false, seatHeight: 0.54, color: 0x8b4513 },
  { id: "bannerhold_oak_bench_dusk", name: "Dusk Oak Bench", theme: "bannerhold", w: 2, l: 1, stackHeights: [0.5625], canWalk: false, canStackOn: false, seatHeight: 0.54, color: 0x5b6672 },
  // Wave A1 colorways (blitz task 6) — same mesh as base, ramp remapped.
  { id: "starter_armchair_sky", name: "Sky Starter Armchair", theme: "starter", w: 1, l: 1, stackHeights: [0.9375], canWalk: false, canStackOn: false, seatHeight: 0.42, color: 0x3f5e9e },
  { id: "starter_coffee_table_walnut", name: "Walnut Coffee Table", theme: "starter", w: 1, l: 1, stackHeights: [0.40625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "starter_entry_mat_sunny", name: "Sunny Entry Mat", theme: "starter", w: 1, l: 1, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0xdaa520 },
  { id: "starter_floor_lamp_mint", name: "Mint Floor Lamp", theme: "starter", w: 1, l: 1, stackHeights: [1.625, 1.625], canWalk: false, canStackOn: false, seatHeight: null, interaction: "toggle", color: 0x2e8b57 },
  { id: "cafe_espresso_machine_copper", name: "Copper Espresso Machine", theme: "cafe", w: 1, l: 1, stackHeights: [1], canWalk: false, canStackOn: false, seatHeight: null, interaction: "vend", vend: { item: "drink_coffee", price: 1 }, color: 0xc2a36b },
  { id: "cafe_bakery_island_sage", name: "Sage Bakery Island", theme: "cafe", w: 2, l: 1, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: null, color: 0x2e8b57 },
  { id: "cafe_bistro_table_terracotta", name: "Terracotta Bistro Table", theme: "cafe", w: 1, l: 1, stackHeights: [0.78125], canWalk: false, canStackOn: false, seatHeight: null, color: 0xaa3333 },
  { id: "cafe_bistro_chair_cream", name: "Cream Bistro Chair", theme: "cafe", w: 1, l: 1, stackHeights: [1], canWalk: false, canStackOn: false, seatHeight: 0.52, color: 0x9c9484 },
  { id: "cafe_pastry_case_walnut", name: "Walnut Pastry Case", theme: "cafe", w: 1, l: 1, stackHeights: [1.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "cafe_barista_stool_honey", name: "Honey Barista Stool", theme: "cafe", w: 1, l: 1, stackHeights: [0.71875], canWalk: false, canStackOn: false, seatHeight: 0.7, color: 0xdaa520 },
  { id: "bedroom_bed_frame_blush", name: "Blush Bed Frame", theme: "bedroom", w: 1, l: 2, stackHeights: [0.90625], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0xaa3333 },
  { id: "bedroom_dresser_ivory", name: "Ivory Dresser", theme: "bedroom", w: 1, l: 1, stackHeights: [0.90625], canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484 },
  { id: "bedroom_nightstand_walnut", name: "Walnut Nightstand", theme: "bedroom", w: 1, l: 1, stackHeights: [0.5], canWalk: false, canStackOn: false, seatHeight: null, color: 0x8b4513 },
  { id: "bedroom_wardrobe_mist", name: "Mist Wardrobe", theme: "bedroom", w: 2, l: 1, stackHeights: [2.125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x5b6672 },
  { id: "bedroom_vanity_ivory", name: "Ivory Vanity", theme: "bedroom", w: 1, l: 1, stackHeights: [1.3125], canWalk: false, canStackOn: false, seatHeight: null, color: 0x9c9484 },
  { id: "bedroom_rug_dusk", name: "Dusk Bedroom Rug", theme: "bedroom", w: 2, l: 2, stackHeights: [0.0625], canWalk: true, canStackOn: true, seatHeight: null, color: 0x3f5e9e },
  { id: "bedroom_table_lamp_sage", name: "Sage Table Lamp", theme: "bedroom", w: 1, l: 1, stackHeights: [0.875, 0.875], canWalk: false, canStackOn: false, seatHeight: null, interaction: "toggle", color: 0x2e8b57 },
  { id: "bedroom_bench_linen", name: "Linen Bedroom Bench", theme: "bedroom", w: 1, l: 1, stackHeights: [0.46875], canWalk: false, canStackOn: false, seatHeight: 0.46, color: 0x9c9484 },
  { id: "bedroom_reading_chair_plum", name: "Plum Reading Chair", theme: "bedroom", w: 1, l: 1, stackHeights: [1.21875], canWalk: false, canStackOn: false, seatHeight: 0.44, color: 0x7a3e9d },
];

// Wall items (#203). span, plane and mount are read off the render by tools/artgen/postpass.ts,
// which prints the line to paste — never measure a parallelogram by hand. plane is the drawn size
// in the wall plane and mount the offsets it was authored at, both in scale-64 px.
export const WALL_CATALOG: WallDef[] = [
  { id: "wall_art",      name: "Wall Art",      theme: "wall_art", span: 1, plane: { w: 26, h: 23 }, mount: { u: 2, v: 35 }, color: 0xdaa520 },
  { id: "poster",        name: "Poster",        theme: "wall_art", span: 1, plane: { w: 24, h: 29 }, mount: { u: 4, v: 34 }, color: 0xaa3333 },
  { id: "record_trophy", name: "Record Trophy", theme: "wall_art", span: 1, plane: { w: 22, h: 21 }, mount: { u: 4, v: 35 }, color: 0x3f5e9e },
  { id: "wall_shelf",    name: "Wall Shelf",    theme: "wall_art", span: 1, plane: { w: 26, h: 13 }, mount: { u: 0, v: 46 }, color: 0xb5651d },
  { id: "wall_art_gilded", name: "Gallery Piece", theme: "wall_art", span: 1, plane: { w: 26, h: 23 }, mount: { u: 2, v: 35 }, color: 0x9c9484 },
  // Lodge round 2 (#323).
  { id: "wall_clock",    name: "Lodge Clock",   theme: "lodge", span: 1, plane: { w: 24, h: 28 }, mount: { u: 2, v: 36 }, color: 0xb5651d },
  { id: "antlers",       name: "Antler Mount",  theme: "lodge", span: 1, plane: { w: 28, h: 37 }, mount: { u: 0, v: 24 }, color: 0xc2a36b },
  // Penthouse suites (#356).
  { id: "sconce_deco",      name: "Deco Sconce",      theme: "penthouse", span: 1, plane: { w: 26, h: 16 }, mount: { u: 0, v: 39 }, color: 0xdaa520 },
  { id: "wallmirror_deco",  name: "Sunburst Mirror",  theme: "penthouse", span: 1, plane: { w: 24, h: 19 }, mount: { u: 4, v: 38 }, color: 0xdaa520 },
  { id: "sconce_deco_onyx", name: "Onyx Deco Sconce", theme: "penthouse", span: 1, plane: { w: 26, h: 16 }, mount: { u: 0, v: 39 }, color: 0x4a4d55 },
  // Jazz Lounge (#358).
  { id: "neon_sign",     name: "Neon Sign",     theme: "lounge", span: 1, plane: { w: 26, h: 28 }, mount: { u: 2, v: 34 }, color: 0xdaa520 },
  { id: "stage_curtain", name: "Stage Curtain", theme: "lounge", span: 1, plane: { w: 26, h: 32 }, mount: { u: 2, v: 33 }, color: 0xaa3333 },
  { id: "stage_curtain_plum", name: "Plum Stage Curtain", theme: "lounge", span: 1, plane: { w: 26, h: 32 }, mount: { u: 2, v: 33 }, color: 0x7a3e9d },
  // Bannerhold pilot wall (blitz task 5): a hanging heraldic banner, original charge.
  // Wave A1 walls.
  { id: "starter_wall_clock", name: "Starter Wall Clock", theme: "starter", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 40 }, color: 0xb5651d },
  { id: "starter_poster_set", name: "Starter Poster Set", theme: "starter", span: 1, plane: { w: 24, h: 17 }, mount: { u: 4, v: 39 }, color: 0xaa3333 },
  { id: "cafe_menu_board", name: "Menu Board", theme: "cafe", span: 1, plane: { w: 26, h: 23 }, mount: { u: 2, v: 35 }, color: 0x4a4d55 },
  { id: "cafe_chalk_art", name: "Chalk Art", theme: "cafe", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0x4a4d55 },
  { id: "cafe_cup_shelf", name: "Cup Shelf", theme: "cafe", span: 1, plane: { w: 28, h: 6 }, mount: { u: 0, v: 47 }, color: 0xb5651d },
  { id: "cafe_tile_mural", name: "Tile Mural", theme: "cafe", span: 1, plane: { w: 26, h: 23 }, mount: { u: 2, v: 35 }, color: 0x9c9484 },
  { id: "cafe_herb_pressing", name: "Herb Pressing", theme: "cafe", span: 1, plane: { w: 18, h: 17 }, mount: { u: 6, v: 39 }, color: 0x2e8b57 },
  { id: "bedroom_mirror", name: "Bedroom Mirror", theme: "bedroom", span: 1, plane: { w: 14, h: 26 }, mount: { u: 8, v: 36 }, color: 0xdaa520 },
  { id: "bedroom_wall_sconce", name: "Wall Sconce", theme: "bedroom", span: 1, plane: { w: 10, h: 13 }, mount: { u: 8, v: 42 }, color: 0xdaa520 },
  { id: "bedroom_tapestry", name: "Tapestry", theme: "bedroom", span: 1, plane: { w: 22, h: 23 }, mount: { u: 4, v: 35 }, color: 0x7a3e9d },
  { id: "bedroom_clock", name: "Bedroom Clock", theme: "bedroom", span: 1, plane: { w: 16, h: 13 }, mount: { u: 6, v: 41 }, color: 0x9c9484 },
  { id: "bedroom_dream_print", name: "Dream Print", theme: "bedroom", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0x3f5e9e },
  { id: "starter_wall_shelf", name: "Starter Wall Shelf", theme: "starter", span: 1, plane: { w: 28, h: 5 }, mount: { u: 0, v: 45 }, color: 0xb5651d },
  { id: "cafe_neon_cup", name: "Neon Cup", theme: "cafe", span: 1, plane: { w: 14, h: 12 }, mount: { u: 8, v: 42 }, color: 0x2f8f8f },
  { id: "bedroom_photo_wall", name: "Photo Wall", theme: "bedroom", span: 1, plane: { w: 22, h: 9 }, mount: { u: 4, v: 41 }, color: 0x3f5e9e },
  { id: "bedroom_shelf", name: "Bedroom Shelf", theme: "bedroom", span: 1, plane: { w: 28, h: 4 }, mount: { u: 0, v: 47 }, color: 0xb5651d },
  { id: "casino_neon_dice", name: "Neon Dice", theme: "casino", span: 1, plane: { w: 10, h: 9 }, mount: { u: 10, v: 44 }, color: 0x2f8f8f },
  // Wave A2 walls: casino + wall_art gallery.
  { id: "casino_card_mural", name: "Card Mural", theme: "casino", span: 1, plane: { w: 24, h: 23 }, mount: { u: 4, v: 36 }, color: 0x4a4d55 },
  { id: "casino_gold_sconce", name: "Gold Sconce", theme: "casino", span: 1, plane: { w: 10, h: 13 }, mount: { u: 8, v: 42 }, color: 0xdaa520 },
  { id: "casino_velvet_drape", name: "Velvet Drape", theme: "casino", span: 1, plane: { w: 22, h: 25 }, mount: { u: 4, v: 36 }, color: 0xaa3333 },
  { id: "casino_marquee_sign", name: "Marquee Sign", theme: "casino", span: 1, plane: { w: 22, h: 12 }, mount: { u: 4, v: 40 }, color: 0x4a4d55 },
  { id: "wall_art_print_aurora", name: "Aurora Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_bloom", name: "Bloom Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_circuit", name: "Circuit Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_dune", name: "Dune Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_ember", name: "Ember Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_fjord", name: "Fjord Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_grove", name: "Grove Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_harbor", name: "Harbor Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_iris", name: "Iris Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_juniper", name: "Juniper Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_kelp", name: "Kelp Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_lumen", name: "Lumen Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_mesa", name: "Mesa Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_north", name: "North Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_onyx", name: "Onyx Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_prism", name: "Prism Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_quill", name: "Quill Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_ridge", name: "Ridge Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_sol", name: "Sol Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_print_tide", name: "Tide Print", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xb5651d },
  { id: "wall_art_triptych_aurora_left", name: "Aurora Triptych Left", theme: "wall_art", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_triptych_aurora_center", name: "Aurora Triptych Center", theme: "wall_art", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_triptych_aurora_right", name: "Aurora Triptych Right", theme: "wall_art", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_triptych_tide_left", name: "Tide Triptych Left", theme: "wall_art", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_triptych_tide_center", name: "Tide Triptych Center", theme: "wall_art", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_triptych_tide_right", name: "Tide Triptych Right", theme: "wall_art", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_gallery_clock", name: "Gallery Clock", theme: "wall_art", span: 1, plane: { w: 18, h: 17 }, mount: { u: 6, v: 39 }, color: 0xb5651d },
  { id: "wall_art_sculpture_relief", name: "Sculpture Relief", theme: "wall_art", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0x5b6672 },
  // Wave A4 walls.
  { id: "penthouse_skyline_art", name: "Skyline Art", theme: "penthouse", span: 1, plane: { w: 24, h: 18 }, mount: { u: 4, v: 37 }, color: 0x3f5e9e },
  { id: "penthouse_gold_mirror", name: "Gold Mirror", theme: "penthouse", span: 1, plane: { w: 14, h: 22 }, mount: { u: 8, v: 36 }, color: 0xdaa520 },
  { id: "penthouse_sconce", name: "Penthouse Sconce", theme: "penthouse", span: 1, plane: { w: 10, h: 9 }, mount: { u: 8, v: 43 }, color: 0xdaa520 },
  { id: "penthouse_marble_relief", name: "Marble Relief", theme: "penthouse", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0xcbc0ac },
  { id: "lounge_neon_note", name: "Neon Note", theme: "lounge", span: 1, plane: { w: 14, h: 16 }, mount: { u: 8, v: 39 }, color: 0xaa3333 },
  { id: "lounge_stage_drape", name: "Stage Drape", theme: "lounge", span: 1, plane: { w: 24, h: 26 }, mount: { u: 4, v: 36 }, color: 0x3f5e9e },
  { id: "lounge_vinyl_print", name: "Vinyl Print", theme: "lounge", span: 1, plane: { w: 18, h: 16 }, mount: { u: 6, v: 39 }, color: 0x4a4d55 },
  { id: "lounge_disco_ball", name: "Disco Ball", theme: "lounge", span: 1, plane: { w: 12, h: 13 }, mount: { u: 6, v: 39 }, color: 0x8d9eb1 },
  // Wave A3 walls.
  { id: "lodge_antler_mount", name: "Antler Mount", theme: "lodge", span: 1, plane: { w: 12, h: 12 }, mount: { u: 8, v: 40 }, color: 0xb5651d },
  { id: "lodge_tapestry", name: "Lodge Tapestry", theme: "lodge", span: 1, plane: { w: 22, h: 23 }, mount: { u: 4, v: 35 }, color: 0x2e8b57 },
  { id: "lodge_wall_lantern", name: "Wall Lantern", theme: "lodge", span: 1, plane: { w: 8, h: 5 }, mount: { u: 10, v: 47 }, color: 0x4a4d55 },
  { id: "lodge_map_frame", name: "Map Frame", theme: "lodge", span: 1, plane: { w: 22, h: 17 }, mount: { u: 4, v: 39 }, color: 0x8b4513 },
  { id: "lodge_wood_carving", name: "Wood Carving", theme: "lodge", span: 1, plane: { w: 14, h: 17 }, mount: { u: 8, v: 39 }, color: 0x8b4513 },
  { id: "pool_tile_mural", name: "Pool Tile Mural", theme: "pool", span: 1, plane: { w: 24, h: 23 }, mount: { u: 4, v: 36 }, color: 0x2f8f8f },
  { id: "pool_lifeguard_sign", name: "Lifeguard Sign", theme: "pool", span: 1, plane: { w: 14, h: 10 }, mount: { u: 8, v: 42 }, color: 0xaa3333 },
  { id: "pool_wave_art", name: "Wave Art", theme: "pool", span: 1, plane: { w: 22, h: 16 }, mount: { u: 4, v: 39 }, color: 0x3f5e9e },
  { id: "pool_sconce", name: "Pool Sconce", theme: "pool", span: 1, plane: { w: 10, h: 9 }, mount: { u: 8, v: 43 }, color: 0x2f8f8f },
  { id: "bannerhold_crest_banner", name: "Bannerhold Crest Banner", theme: "bannerhold", span: 1, plane: { w: 24, h: 24 }, mount: { u: 2, v: 34 }, color: 0xaa3333 },
];

/** What a new account is given, and nothing else. Explicitly listed, never "the whole catalog" —
 *  every def added later must be earned through the Stars sink, not granted for free. */
export const STARTER_GRANT_DEFS: readonly string[] = [
  "chair_basic", "table_basic", "sofa_basic", "plant_basic", "rug_basic",
];

// GAME.md §Price ladder (all tune): entry furni 25, median furni 150.
export const CATALOG_PRICES: ReadonlyMap<string, number> = new Map([
  ["chair_basic", 25],
  ["plant_basic", 25],
  ["rug_basic", 50],
  ["table_basic", 150],
  ["sofa_basic", 150],
  ["casino_stool", 25],
  ["cafe_chair", 25],
  ["lamp_basic", 75],
  ["divider_basic", 75],
  ["cafe_table", 150],
  ["bed_basic", 150],
  ["shelf_basic", 150],
  ["stereo_basic", 150],
  ["casino_table", 300],
  ["arcade_cabinet", 150],
  ["slot_machine", 300],
  ["bar_counter", 300],
  ["fountain", 300],
  ["cafe_chair_crimson", 25],
  ["cafe_chair_navy", 25],
  ["casino_stool_fern", 25],
  ["divider_basic_plum", 75],
  ["poster", 50],
  ["wall_art", 150],
  ["wall_shelf", 150],
  ["record_trophy", 300],
  // Lodge set (#314) and its colorways, on the existing rungs.
  ["railing", 50],
  ["railing_iron", 50],
  ["plant_fern", 75],
  ["plant_fern_exotic", 75],
  ["armchair_lounge", 150],
  ["armchair_lounge_navy", 150],
  ["armchair_lounge_fern", 150],
  ["table_round", 150],
  ["table_round_onyx", 150],
  ["sofa_lodge", 300],
  ["sofa_lodge_plum", 300],
  ["fireplace", 300],
  ["fireplace_stone", 300],
  // Lodge round 2 (#323): wall clutter and the props that go under it.
  ["stool_lodge", 25],
  ["stool_lodge_charcoal", 25],
  ["rug_lodge", 75],
  ["side_table", 75],
  ["side_table_slate", 75],
  ["wall_clock", 150],
  ["antlers", 300],
  // Amenities (#327). The counter is the bar counter's price, since it is the same object recoloured.
  ["sink_basic", 150],
  ["vending_machine", 250],
  ["cafe_counter", 300],
  // Pool & spa deck (#357), on the same rungs the lodge uses: a seat is entry, a 1x1 prop is 75,
  // a 1x1 with contents or a 1x2 is median, and a 2x2 centrepiece is 300 like the fountain.
  ["deck_chair", 25],
  ["deck_chair_crimson", 25],
  ["deck_chair_navy", 25],
  ["pool_ladder", 50],
  ["towel_rack", 75],
  ["towel_rack_linen", 75],
  ["potted_palm", 75],
  ["potted_palm_teal", 75],
  ["sun_lounger", 150],
  ["sun_lounger_crimson", 150],
  ["drinks_trolley", 150],
  ["drinks_trolley_sunset", 150],
  ["parasol_table", 300],
  ["parasol_table_teal", 300],
  ["cabana", 300],
  ["cabana_crimson", 300],
  ["hot_tub", 300],
  ["hot_tub_cedar", 300],
  ["bar_counter_pool", 300],
  // Penthouse suites (#356), on the existing rungs and no higher: the set is luxury by palette,
  // not by price, so its ceiling is the 300 the bar counter and the hearth already sit on. A
  // colorway costs what its base costs — they share a mesh, so they share a rung.
  ["ottoman_deco", 25],
  ["ottoman_deco_ivory", 25],
  ["lamp_deco", 75],
  ["mirror_standing", 75],
  ["mirror_standing_plum", 75],
  ["barcart_deco", 150],
  ["vanity_deco", 150],
  ["dresser_deco", 150],
  ["dresser_deco_navy", 150],
  ["screen_deco", 150],
  ["screen_deco_jade", 150],
  ["sconce_deco", 150],
  ["sconce_deco_onyx", 150],
  ["bed_grand", 300],
  ["bed_grand_plum", 300],
  ["chaise_deco", 300],
  ["chaise_deco_crimson", 300],
  ["armoire_deco", 300],
  ["armoire_deco_ivory", 300],
  ["wallmirror_deco", 300],
  // Jazz Lounge (#358). Props sit on the existing rungs; the three stage pieces open two new ones
  // between 300 and prestige, because a room-defining instrument that is not account-bound has
  // nowhere to sit otherwise. The grand piano at 900 is 1.5 days of the earn ceiling — a weekend,
  // where billiards at 3,300 is weeks — and it stays well clear of prestige so it can be traded.
  ["mic_stand", 75],
  ["stage_platform", 150],
  ["stage_platform_parquet", 150],
  ["cocktail_table", 150],
  ["cocktail_table_walnut", 150],
  ["stage_light", 150],
  ["stage_light_plum", 150],
  ["neon_sign", 150],
  ["speaker_column", 250],
  ["speaker_column_vintage", 250],
  ["stage_curtain", 250],
  ["stage_curtain_plum", 250],
  ["double_bass", 300],
  ["double_bass_ebony", 300],
  ["velvet_booth", 400],
  ["velvet_booth_plum", 400],
  ["velvet_booth_charcoal", 400],
  ["drum_kit", 500],
  ["grand_piano", 900],
  ["grand_piano_oak", 900],
  // Prestige (#210). GAME.md §Price ladder puts the flagship at 3,300 — 5.5× the daily earn
  // ceiling, so it is weeks of play rather than an afternoon's.
  ["billiards_table", 3300],
  ["penthouse_candelabra", 1800],
  // Bannerhold pilots (blitz task 5): the colorway costs what its base costs.
  ["bannerhold_oak_bench", 50],
  ["bannerhold_oak_bench_dusk", 50],
  ["bannerhold_crest_banner", 75],
  // Wave A1 (blitz task 6). Colorways cost their base; the Suite Basics reward is unpriced.
  ["starter_armchair", 50],
  ["starter_coffee_table", 75],
  ["starter_entry_mat", 25],
  ["starter_floor_lamp", 50],
  ["starter_bookcase", 75],
  ["starter_wall_clock", 25],
  ["starter_poster_set", 25],
  ["starter_wall_shelf", 50],
  ["cafe_espresso_machine", 400],
  ["cafe_bakery_island", 250],
  ["cafe_bistro_table", 75],
  ["cafe_bistro_chair", 50],
  ["cafe_pastry_case", 150],
  ["cafe_barista_stool", 50],
  ["cafe_potted_herb", 25],
  ["cafe_woven_rug", 75],
  ["cafe_menu_board", 75],
  ["cafe_chalk_art", 25],
  ["cafe_cup_shelf", 50],
  ["cafe_neon_cup", 150],
  ["cafe_tile_mural", 150],
  ["cafe_herb_pressing", 25],
  ["bedroom_bed_frame", 300],
  ["bedroom_dresser", 250],
  ["bedroom_nightstand", 75],
  ["bedroom_wardrobe", 300],
  ["bedroom_vanity", 250],
  ["bedroom_rug", 75],
  ["bedroom_table_lamp", 50],
  ["bedroom_bench", 150],
  ["bedroom_reading_chair", 150],
  ["bedroom_desk", 250],
  ["bedroom_mirror", 75],
  ["bedroom_photo_wall", 50],
  ["bedroom_wall_sconce", 50],
  ["bedroom_tapestry", 75],
  ["bedroom_shelf", 50],
  ["bedroom_clock", 25],
  ["bedroom_dream_print", 25],
  ["starter_armchair_sky", 50],
  ["starter_coffee_table_walnut", 75],
  ["starter_entry_mat_sunny", 25],
  ["starter_floor_lamp_mint", 50],
  ["cafe_espresso_machine_copper", 400],
  ["cafe_bakery_island_sage", 250],
  ["cafe_bistro_table_terracotta", 75],
  ["cafe_bistro_chair_cream", 50],
  ["cafe_pastry_case_walnut", 150],
  ["cafe_barista_stool_honey", 50],
  ["bedroom_bed_frame_blush", 300],
  ["bedroom_dresser_ivory", 250],
  ["bedroom_nightstand_walnut", 75],
  ["bedroom_wardrobe_mist", 300],
  ["bedroom_rug_dusk", 75],
  ["bedroom_table_lamp_sage", 50],
  ["bedroom_bench_linen", 150],
  ["bedroom_reading_chair_plum", 150],
  // Wave A2 (blitz task 7).
  ["casino_card_table", 300],
  ["casino_dice_table", 250],
  ["casino_chip_rack", 75],
  ["casino_dealer_chair", 150],
  ["casino_velvet_rope", 75],
  ["casino_round_rug", 150],
  ["casino_pendant_lamp", 75],
  ["casino_banquette", 150],
  ["casino_neon_dice", 150],
  ["casino_card_mural", 150],
  ["casino_gold_sconce", 75],
  ["casino_velvet_drape", 75],
  ["casino_marquee_sign", 150],
  ["wall_art_print_aurora", 75],
  ["wall_art_print_bloom", 50],
  ["wall_art_print_circuit", 75],
  ["wall_art_print_dune", 25],
  ["wall_art_print_ember", 75],
  ["wall_art_print_fjord", 50],
  ["wall_art_print_grove", 50],
  ["wall_art_print_harbor", 75],
  ["wall_art_print_iris", 50],
  ["wall_art_print_juniper", 25],
  ["wall_art_print_kelp", 50],
  ["wall_art_print_lumen", 75],
  ["wall_art_print_mesa", 25],
  ["wall_art_print_north", 75],
  ["wall_art_print_onyx", 50],
  ["wall_art_print_prism", 75],
  ["wall_art_print_quill", 25],
  ["wall_art_print_ridge", 50],
  ["wall_art_print_sol", 75],
  ["wall_art_print_tide", 50],
  ["wall_art_triptych_aurora_left", 50],
  ["wall_art_triptych_aurora_center", 50],
  ["wall_art_triptych_aurora_right", 50],
  ["wall_art_triptych_tide_left", 50],
  ["wall_art_triptych_tide_center", 50],
  ["wall_art_triptych_tide_right", 50],
  ["wall_art_gallery_clock", 75],
  ["wall_art_sculpture_relief", 150],
  ["casino_card_table_emerald", 300],
  ["casino_dice_table_noir", 250],
  ["casino_chip_rack_gold", 75],
  ["casino_dealer_chair_oxblood", 150],
  ["casino_velvet_rope_crimson", 75],
  ["casino_round_rug_onyx", 150],
  ["casino_pendant_lamp_brass", 75],
  // Wave A3 (blitz task 8). Rewards unpriced.
  ["lodge_wood_stove", 400],
  ["lodge_log_bed", 300],
  ["lodge_antler_chair", 250],
  ["lodge_wood_table", 150],
  ["lodge_fur_rug", 150],
  ["lodge_lantern", 75],
  ["lodge_bench", 75],
  ["lodge_antler_mount", 150],
  ["lodge_tapestry", 150],
  ["lodge_wall_lantern", 50],
  ["lodge_map_frame", 75],
  ["lodge_wood_carving", 75],
  ["pool_hanging_chair", 150],
  ["pool_shade_sail", 75],
  ["pool_side_table", 50],
  ["pool_float_rack", 75],
  ["pool_towel_cart", 75],
  ["pool_mosaic_rug", 150],
  ["pool_tile_mural", 150],
  ["pool_lifeguard_sign", 75],
  ["pool_wave_art", 75],
  ["pool_sconce", 50],
  ["lodge_log_bed_pine", 300],
  ["lodge_antler_chair_russet", 250],
  ["lodge_wood_table_cedar", 150],
  ["lodge_fur_rug_grey", 150],
  ["lodge_lantern_copper", 75],
  ["pool_hanging_chair_coral", 150],
  ["pool_shade_sail_aqua", 75],
  ["pool_side_table_teal", 50],
  ["pool_float_rack_sunny", 75],
  ["pool_towel_cart_white", 75],
  // Wave A4 (blitz task 9). Rewards + unreleased prestige unpriced.
  ["penthouse_sofa", 400],
  ["penthouse_marble_table", 300],
  ["penthouse_dining_chair", 250],
  ["penthouse_bar", 400],
  ["penthouse_silk_rug", 250],
  ["penthouse_telescope", 300],
  ["penthouse_skyline_art", 150],
  ["penthouse_gold_mirror", 150],
  ["penthouse_sconce", 75],
  ["penthouse_marble_relief", 150],
  ["lounge_vibraphone", 500],
  ["lounge_velvet_sofa", 300],
  ["lounge_record_console", 150],
  ["lounge_bar_stool", 75],
  ["lounge_floor_lamp", 75],
  ["lounge_stage_rug", 150],
  ["lounge_neon_note", 150],
  ["lounge_stage_drape", 75],
  ["lounge_vinyl_print", 75],
  ["lounge_disco_ball", 150],
  ["prestige_gold_throne", 3300],
  ["penthouse_sofa_ivory", 400],
  ["penthouse_marble_table_noir", 300],
  ["penthouse_dining_chair_champagne", 250],
  ["penthouse_bar_midnight", 400],
  ["penthouse_silk_rug_pearl", 250],
  ["lounge_velvet_sofa_berry", 300],
  ["lounge_record_console_smoke", 150],
  ["lounge_bar_stool_brass", 75],
  ["lounge_floor_lamp_amber", 75],
  ["lounge_stage_rug_noir", 150],
]);

/** Every catalog id not in CATALOG_PRICES must be listed here with a reason — checked by
 *  furni.test.ts so a missing price stays a deliberate choice, not a silent gap (it would
 *  otherwise show nowhere in the shop and value at 0 Stars in limits.ts's laundering wall). */
export const UNPRICED: ReadonlySet<string> = new Set([
  // Luck Lever exclusives (#210): won, never sold.
  "arcade_cabinet_plum",
  "fountain_gilded",
  // Collection-set rewards (#210): minted account-bound on completion, obtainable no other way.
  "cafe_table_marble",
  "casino_table_onyx",
  "wall_art_gilded",
  // R-26 (#429): chance furni is never player-purchasable. Only the house layout places one, so a
  // furni instance can never become a player-owned gambling machine.
  "grand_wheel",
  "wheel_podium",
  // R-26 (#428): the blackjack table pays out of the house's bank, so the house is the only thing
  // that may own one. A player-owned table is a player holding the dealer's side of every hand.
  "blackjack_table",
  // Suite Basics reward (blitz task 6): minted on completion, never sold.
  "bedroom_vanity_ivory",
  "lodge_wood_stove_slate",
  "pool_mosaic_rug_lagoon",
  "penthouse_telescope_copper",
  "lounge_vibraphone_ivory",
  "prestige_marble_fountain",
  "prestige_crystal_screen",
  "prestige_obsidian_table",
  "prestige_velvet_daybed",
  "prestige_gold_throne_onyx",
  "prestige_marble_fountain_moonstone",
  "prestige_crystal_screen_amber",
]);

/** House fixtures (R-26, #429): placed by furnish.ts and by nothing else — no price, no prize, no
 *  set. They are the fourth and last route a def may take out of the obtainability test, and the
 *  only one that ends with the player never owning the item.
 *
 *  slot_machine is NOT here and is sold at 300, because it carries no `interaction` — it is
 *  casino-shaped scenery. The line R-26 draws is the verb: a def that resolves a wager belongs to
 *  the house, or the house has sold a player its own edge. */
export const HOUSE_FIXTURE_DEFS: ReadonlySet<string> = new Set([
  "grand_wheel",
  "wheel_podium",
  "blackjack_table",
]);

/** Bought like anything else, but minted account-bound: these never enter the trade economy, so
 *  the Stars they absorb are gone rather than recirculating as goods (GAME.md §Sinks). */
export const PRESTIGE_DEFS: ReadonlySet<string> = new Set([
  "billiards_table",
  "penthouse_candelabra",
  "prestige_gold_throne",
  "prestige_marble_fountain",
  "prestige_crystal_screen",
  "prestige_obsidian_table",
  "prestige_velvet_daybed",
  "prestige_gold_throne_onyx",
  "prestige_marble_fountain_moonstone",
  "prestige_crystal_screen_amber",
]);

/** Content-blitz ledger (docs/plans/2026-08-11-furniture-content-blitz-catalog.md). Each wave
 *  adds its ids here in the same commit as its defs and assets; content-blitz.test.ts gates the
 *  routing of every landed id. */
export const LANDED_BLITZ_IDS: ReadonlySet<string> = new Set<string>([
  // Task 5 pilots.
  "bannerhold_oak_bench",
  "bannerhold_oak_bench_dusk",
  "bannerhold_crest_banner",
  // Task 6 wave A1.
  "starter_armchair",
  "starter_coffee_table",
  "starter_entry_mat",
  "starter_floor_lamp",
  "starter_bookcase",
  "starter_wall_clock",
  "starter_poster_set",
  "starter_wall_shelf",
  "cafe_espresso_machine",
  "cafe_bakery_island",
  "cafe_bistro_table",
  "cafe_bistro_chair",
  "cafe_pastry_case",
  "cafe_barista_stool",
  "cafe_potted_herb",
  "cafe_woven_rug",
  "cafe_menu_board",
  "cafe_chalk_art",
  "cafe_cup_shelf",
  "cafe_neon_cup",
  "cafe_tile_mural",
  "cafe_herb_pressing",
  "bedroom_bed_frame",
  "bedroom_dresser",
  "bedroom_nightstand",
  "bedroom_wardrobe",
  "bedroom_vanity",
  "bedroom_rug",
  "bedroom_table_lamp",
  "bedroom_bench",
  "bedroom_reading_chair",
  "bedroom_desk",
  "bedroom_mirror",
  "bedroom_photo_wall",
  "bedroom_wall_sconce",
  "bedroom_tapestry",
  "bedroom_shelf",
  "bedroom_clock",
  "bedroom_dream_print",
  "starter_armchair_sky",
  "starter_coffee_table_walnut",
  "starter_entry_mat_sunny",
  "starter_floor_lamp_mint",
  "cafe_espresso_machine_copper",
  "cafe_bakery_island_sage",
  "cafe_bistro_table_terracotta",
  "cafe_bistro_chair_cream",
  "cafe_pastry_case_walnut",
  "cafe_barista_stool_honey",
  "bedroom_bed_frame_blush",
  "bedroom_dresser_ivory",
  "bedroom_nightstand_walnut",
  "bedroom_wardrobe_mist",
  "bedroom_rug_dusk",
  "bedroom_table_lamp_sage",
  "bedroom_bench_linen",
  "bedroom_reading_chair_plum",
  "bedroom_vanity_ivory",
  // Task 7 wave A2.
  "casino_card_table",
  "casino_dice_table",
  "casino_chip_rack",
  "casino_dealer_chair",
  "casino_velvet_rope",
  "casino_round_rug",
  "casino_pendant_lamp",
  "casino_banquette",
  "casino_neon_dice",
  "casino_card_mural",
  "casino_gold_sconce",
  "casino_velvet_drape",
  "casino_marquee_sign",
  "wall_art_print_aurora",
  "wall_art_print_bloom",
  "wall_art_print_circuit",
  "wall_art_print_dune",
  "wall_art_print_ember",
  "wall_art_print_fjord",
  "wall_art_print_grove",
  "wall_art_print_harbor",
  "wall_art_print_iris",
  "wall_art_print_juniper",
  "wall_art_print_kelp",
  "wall_art_print_lumen",
  "wall_art_print_mesa",
  "wall_art_print_north",
  "wall_art_print_onyx",
  "wall_art_print_prism",
  "wall_art_print_quill",
  "wall_art_print_ridge",
  "wall_art_print_sol",
  "wall_art_print_tide",
  "wall_art_triptych_aurora_left",
  "wall_art_triptych_aurora_center",
  "wall_art_triptych_aurora_right",
  "wall_art_triptych_tide_left",
  "wall_art_triptych_tide_center",
  "wall_art_triptych_tide_right",
  "wall_art_gallery_clock",
  "wall_art_sculpture_relief",
  "casino_card_table_emerald",
  "casino_dice_table_noir",
  "casino_chip_rack_gold",
  "casino_dealer_chair_oxblood",
  "casino_velvet_rope_crimson",
  "casino_round_rug_onyx",
  "casino_pendant_lamp_brass",
  // Task 8 wave A3.
  "lodge_wood_stove",
  "lodge_log_bed",
  "lodge_antler_chair",
  "lodge_wood_table",
  "lodge_fur_rug",
  "lodge_lantern",
  "lodge_bench",
  "lodge_antler_mount",
  "lodge_tapestry",
  "lodge_wall_lantern",
  "lodge_map_frame",
  "lodge_wood_carving",
  "pool_hanging_chair",
  "pool_shade_sail",
  "pool_side_table",
  "pool_float_rack",
  "pool_towel_cart",
  "pool_mosaic_rug",
  "pool_tile_mural",
  "pool_lifeguard_sign",
  "pool_wave_art",
  "pool_sconce",
  "lodge_log_bed_pine",
  "lodge_antler_chair_russet",
  "lodge_wood_table_cedar",
  "lodge_fur_rug_grey",
  "lodge_lantern_copper",
  "pool_hanging_chair_coral",
  "pool_shade_sail_aqua",
  "pool_side_table_teal",
  "pool_float_rack_sunny",
  "pool_towel_cart_white",
  "lodge_wood_stove_slate",
  "pool_mosaic_rug_lagoon",
  // Task 9 wave A4.
  "prestige_marble_fountain",
  "prestige_crystal_screen",
  "prestige_obsidian_table",
  "prestige_velvet_daybed",
  "penthouse_sofa",
  "penthouse_marble_table",
  "penthouse_dining_chair",
  "penthouse_bar",
  "penthouse_silk_rug",
  "penthouse_telescope",
  "penthouse_skyline_art",
  "penthouse_gold_mirror",
  "penthouse_sconce",
  "penthouse_marble_relief",
  "lounge_vibraphone",
  "lounge_velvet_sofa",
  "lounge_record_console",
  "lounge_bar_stool",
  "lounge_floor_lamp",
  "lounge_stage_rug",
  "lounge_neon_note",
  "lounge_stage_drape",
  "lounge_vinyl_print",
  "lounge_disco_ball",
  "prestige_gold_throne",
  "penthouse_sofa_ivory",
  "penthouse_marble_table_noir",
  "penthouse_dining_chair_champagne",
  "penthouse_bar_midnight",
  "penthouse_silk_rug_pearl",
  "lounge_velvet_sofa_berry",
  "lounge_record_console_smoke",
  "lounge_bar_stool_brass",
  "lounge_floor_lamp_amber",
  "lounge_stage_rug_noir",
  "penthouse_telescope_copper",
  "lounge_vibraphone_ivory",
  "prestige_gold_throne_onyx",
  "prestige_marble_fountain_moonstone",
  "prestige_crystal_screen_amber",
  "penthouse_telescope_copper",
  "lounge_vibraphone_ivory",
  "prestige_marble_fountain",
  "prestige_crystal_screen",
  "prestige_obsidian_table",
  "prestige_velvet_daybed",
  "prestige_gold_throne_onyx",
  "prestige_marble_fountain_moonstone",
  "prestige_crystal_screen_amber",

]);
/** Landed blitz decor tiles (the plan's Appendix B). */
export const LANDED_DECOR_IDS: ReadonlySet<string> = new Set<string>([
  "floor_starter_oak",
  "floor_starter_sand_check",
  "wall_starter_plaster_blue",
  "wall_starter_pinstripe",
  "floor_cafe_checker_cream",
  "floor_cafe_terracotta",
  "wall_cafe_subway_tile",
  "wall_cafe_awning_stripe",
  "floor_bedroom_oak_herringbone",
  "floor_bedroom_soft_check",
  "floor_bedroom_moon_inlay",
  "wall_bedroom_linen",
  "wall_bedroom_cloud",
  "wall_bedroom_pinstripe",
  "floor_casino_felt_diamond",
  "floor_casino_card_suit",
  "wall_casino_deco_fan",
  "wall_casino_crimson_panel",
  "floor_gallery_terrazzo",
  "floor_gallery_oak",
  "wall_gallery_canvas",
  "wall_gallery_picture_rail",
  "floor_lodge_flagstone",
  "floor_lodge_pine",
  "wall_lodge_plank",
  "wall_lodge_compass",
  "floor_pool_shell_tile",
  "floor_pool_wave_mosaic",
  "wall_pool_cabana_stripe",
  "wall_pool_sun_tile",
  "floor_penthouse_marble_fan",
  "floor_penthouse_parquet",
  "wall_penthouse_deco_fan",
  "wall_penthouse_silk_panel",
  "floor_lounge_parquet_dark",
  "floor_lounge_stage_star",
  "wall_lounge_velvet_panel",
  "wall_lounge_music_note",
]);
/** The staged prestige line: the eight blitz prestige fixtures land together but surface in the
 *  catalog one per wave. An id here is priced in CATALOG_PRICES; an id absent is staged in
 *  UNPRICED. The two pre-blitz prestige fixtures above are unaffected — they were always on sale. */
export const RELEASED_PRESTIGE_IDS: ReadonlySet<string> = new Set<string>([  "prestige_gold_throne",
]);
